#!/bin/bash -x

. shared.sh

postgres_configure() {
  chkconfig postgresql on
  service postgresql initdb

  echo "listen_addresses = '*'" >>/var/lib/pgsql/data/postgresql.conf
  cat >>/var/lib/pgsql/data/pg_hba.conf <<'EOF'
host all postgres 0.0.0.0/0 reject
host all all 0.0.0.0/0 md5
EOF

  service postgresql start
}

db_create() {
  su - postgres <<EOF
createuser -s $2
createdb -O $2 $1
echo "ALTER USER $2 PASSWORD '$3'" | psql
EOF
}

register_channels rhel-x86_64-server-6
install_packages postgresql-server

disable_firewall
postgres_configure
db_create ticketmonster admin password
