#!/bin/bash -x

. shared.sh

maven_install() {
  curl -s http://$PROXY_IP_ADDR/apache-maven-3.2.3-bin.tar.gz | (cd /usr/local && tar -xz)
}

nexus_install() {
  curl -s http://$PROXY_IP_ADDR/nexus-2.9.1-02-bundle.tar.gz | (cd /usr/local && tar -xz)

  cat >>/etc/rc.local <<EOF
RUN_AS_USER=root $(echo /usr/local/nexus-*/bin)/nexus start
EOF
}

nexus_configure() {
  sed -i -e "s/\$PROXY_IP_ADDR/$PROXY_IP_ADDR/" nexus.xml

  mkdir /usr/local/sonatype-work/nexus/conf
  cp nexus.xml /usr/local/sonatype-work/nexus/conf
}

nexus_start() {
  RUN_AS_USER=root /usr/local/nexus-*/bin/nexus start

  while ! curl -fsm 1 -o /dev/null http://localhost/nexus; do
    sleep 1
  done
}

register_jenkins_repo() {
  curl -so /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
  rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
}

jenkins_configure_prestart() {
  sed -i -e 's!^JENKINS_ARGS=.*!JENKINS_ARGS="--prefix=/jenkins"!' /etc/sysconfig/jenkins

  sed -i -e "s!\$MAVEN_HOME!$(echo /usr/local/apache-maven-*)!" hudson.tasks.Maven.xml
  cp hudson.tasks.Maven.xml /var/lib/jenkins

  mkdir /var/lib/jenkins/updates
  curl -Ls http://updates.jenkins-ci.org/update-center.json | sed -ne 2p >/var/lib/jenkins/updates/default.json

  mkdir /var/lib/jenkins/.m2
  cp settings.xml /var/lib/jenkins/.m2

  cat >/var/lib/jenkins/.gitconfig <<EOF
[user]
	name = Jenkins
	email = jenkins@ci.demo
EOF

  chown -R jenkins:jenkins /var/lib/jenkins
}

jenkins_start() {
  chkconfig jenkins on
  service jenkins start

  while ! curl -fsm 1 -o /dev/null http://localhost/jenkins; do
    sleep 1
  done
}

jenkins_cli() {
  [ -e /tmp/jenkins-cli.jar ] || curl -so /tmp/jenkins-cli.jar http://localhost/jenkins/jnlpJars/jenkins-cli.jar
  java -jar /tmp/jenkins-cli.jar -s http://localhost/jenkins/ "$@"
}

httpd_configure() {
  cat >/etc/httpd/conf.d/proxy.conf <<EOF
ProxyPass /nexus http://localhost:8081/nexus
ProxyPassReverse /nexus http://localhost:8081/nexus
ProxyPass /jenkins http://localhost:8080/jenkins nocanon
ProxyPassReverse /jenkins http://localhost:8080/jenkins
ProxyTimeout 600
AllowEncodedSlashes On
EOF

  cat >/var/www/html/index.html <<EOF
<p><a href="/nexus">Nexus</a>
<br><a href="/jenkins">Jenkins</a>
EOF

  setsebool httpd_can_network_connect true
  chkconfig httpd on
  service httpd start
}

register_channels rhel-x86_64-server-6 rhel-x86_64-server-6-ost-5
register_jenkins_repo
install_packages bind-utils gettext git httpd java-1.7.0-openjdk-devel jenkins postgresql python-heatclient python-neutronclient python-novaclient
yum_update

register_dns ci demo A $FLOATING_IP_ADDR

httpd_configure

maven_install

nexus_install
nexus_configure
nexus_start

cp keystonerc /etc
chown root:jenkins /etc/keystonerc
chmod 0640 /etc/keystonerc

jenkins_configure_prestart
jenkins_start

jenkins_cli install-plugin build-pipeline-plugin git -deploy

jenkins_cli quiet-down -block

for i in jobs/*; do
  sed -e "s!\$GIT_URL!$GIT_URL!" < "$i" | jenkins_cli create-job "$(basename "$i" .xml)"
done

for i in views/*; do
  jenkins_cli create-view < "$i"
done

jenkins_cli cancel-quiet-down

lokkit -p 80:tcp
