heat_template_version: 2013-05-23

parameters:
  key_name:
    description: Keypair name for server access
    type: string
  public_net:
    description: UUID of public network
    type: string
  private_net:
    description: UUID of private network
    type: string
  image:
    default: rhel-guest-image-6-6.5-20140603.0-heat-agent
    type: string

resources:
  root_server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: m1.small
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: root_port }
      user_data_format: SOFTWARE_CONFIG

  root_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net }

  root_floatingip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net } 
      port_id: { get_resource: root_port }

  root_softwareconfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: { get_file: postgresql.sh }

  root_softwaredeployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      config: { get_resource: root_softwareconfig }
      server: { get_resource: root_server }
      input_values:
        CONF_NODE: root

outputs:
  DATABASE_IP:
    value: { get_attr: [ root_floatingip, floating_ip_address ] }
