heat_template_version: 2013-05-23

parameters:
  key_name:
    description: Keypair name for server access
    type: string
  public_net:
    description: UUID of public network
    type: string
  dns_nameservers:
    description: public DNS servers
    type: comma_delimited_list
  image:
    description: Glance image
    type: string
  ci_ip_address:
    description: IP of CI server
    type: string
  security_groups:
    description: Neutron security groups
    type: comma_delimited_list

resources:
  net_fabric:
    type: Library::Net
    properties:
      public_net: { get_param: public_net }
      cidr: 172.16.2/24
      gateway_ip: 172.16.2.254
      start: 172.16.2.1
      end: 172.16.2.253
      dns_nameservers: { get_param: dns_nameservers }

  root_server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: m1.small
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: root_port }
      user_data_format: SOFTWARE_CONFIG

  root_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_attr: [ net_fabric, id ] }
      security_groups: { get_param: security_groups }

  root_floatingip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net } 
      port_id: { get_resource: root_port }

  root_softwareconfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: tgz
      config: { get_file: fabric.tgz }

  root_softwaredeployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      config: { get_resource: root_softwareconfig }
      server: { get_resource: root_server }
      input_values:
        CONF_CI_IP_ADDR: { get_param: ci_ip_address }

outputs:
  ROOT_IP:
    value: { get_attr: [ root_floatingip, floating_ip_address ] }
