heat_template_version: 2013-05-23

parameters:
  config:
    description: relative path to install script
    type: string
  input_values:
    description: input values to install script
    type: json
  image:
    description: Glance image to use as template
    type: string
  key_name:
    description: Keypair name for server access
    type: string
  network:
    description: UUID of private network
    type: string
  public_net:
    description: UUID of public network (where floating IP is created)
    type: string
  flavor:
    description: Nova flavour
    type: string
    default: m1.tiny

resources:
  server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: port }
      user_data_format: SOFTWARE_CONFIG

  port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: network }

  floatingip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net } 
      port_id: { get_resource: port }

  softwareconfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: { get_param: config }

  softwaredeployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      config: { get_resource: softwareconfig }
      server: { get_resource: server }
      input_values: { get_param: input_values }

outputs:
  id:
    value: { get_resource: server }
    description: ID of created server

  ip:
    value: { get_attr: [ floatingip, floating_ip_address ] }
    description: floating IP of created server

  stdout:
    value: { get_attr: [ softwaredeployment, deploy_stdout ] }
    description: stdout of install script

  stderr:
    value: { get_attr: [ softwaredeployment, deploy_stderr ] }
    description: stdout of install script
