#!/bin/bash -x

. shared.sh

FUSE_VERSION=${FUSE_VERSION:-jboss-fuse-6.1.0.redhat-379}
FUSE_USER=cloud-user

fuse_install() {
  curl -so /tmp/$FUSE_VERSION.zip http://$PROXY_IP_ADDR/jboss-fuse-medium-6.1.0.redhat-379.zip
  unzip -q /tmp/$FUSE_VERSION.zip -d /usr/local
}

fuse_create_admin_user() {
  echo -e "\n$1=$2,admin" >>/usr/local/$FUSE_VERSION/etc/users.properties 
}

fuse_set_nexus() {
  sed -i -e "/^org.ops4j.pax.url.mvn.repositories=/,/[^\]$/ d; $ a\
org.ops4j.pax.url.mvn.repositories=http://$CONF_CI_IP_ADDR/nexus/content/groups/public@id=mirror.repo" /usr/local/$FUSE_VERSION/fabric/import/fabric/configs/versions/1.0/profiles/default/io.fabric8.agent.properties
}

fuse_disable_indexer() {
  sed -i -e '/<feature>hawtio-maven-indexer<\/feature>/ d' /usr/local/$FUSE_VERSION/system/io/hawt/hawtio-karaf/1.2-redhat-379/hawtio-karaf-1.2-redhat-379-features.xml
}

fuse_chown() {
  chown -R $FUSE_USER:$FUSE_USER /usr/local/$FUSE_VERSION
}

fuse_start() {
  su - $FUSE_USER <<EOF
export JAVA_HOME=/usr/lib/jvm/jre-1.7.0

/usr/local/$FUSE_VERSION/bin/start
while ! /usr/local/$FUSE_VERSION/bin/client </dev/null &>/dev/null
do
  sleep 5
done
EOF
}

fuse_create_fabric() {
  su - $FUSE_USER <<EOF
/usr/local/$FUSE_VERSION/bin/client "fabric:create --wait-for-provisioning --resolver manualip --manual-ip $FLOATING_IP_ADDR --profile fabric"
/usr/local/$FUSE_VERSION/bin/client "container-create-child --profile mq-amq root broker"
EOF
}

register_channels rhel-x86_64-server-6
install_packages bind-utils java-1.7.0-openjdk unzip

register_dns $(hostname | cut -d- -f1,2) demo A $FLOATING_IP_ADDR

disable_firewall

fuse_install
fuse_create_admin_user admin admin
fuse_set_nexus
fuse_disable_indexer
fuse_chown
fuse_start
fuse_create_fabric
