#!/bin/bash -x

. shared.sh

ose_register_dns() {
  nsupdate -y HMAC-SHA256:$CONF_DOMAIN:$CONF_BIND_KEY <<EOF
server $CONF_NAMED_IP_ADDR
update delete $1 $2
update add $1 180 $2 $3
send
EOF
}

ose_install() {
  curl -so /tmp/openshift.sh https://raw.githubusercontent.com/openshift/openshift-extras/enterprise-2.1/enterprise/install-scripts/generic/openshift.sh
  chmod 0755 /tmp/openshift.sh
  /tmp/openshift.sh
}

ose_node_configure() {
  sed -i -e 's/^cpu_cfs_quota_us=.*/cpu_cfs_quota_us=-1/' /etc/openshift/resource_limits.conf

  cat >/usr/libexec/openshift/cartridges/jbosseap/versions/shared/standalone/configuration/settings.base.xml <<EOF
<settings>
  <mirrors>
    <mirror>
      <mirrorOf>*</mirrorOf>
      <url>http://$PROXY_IP_ADDR:8081/nexus/content/groups/public</url>
      <id>mirror</id>
    </mirror>
  </mirrors>
</settings>
EOF

  cat >/usr/libexec/openshift/cartridges/jbossews/usr/versions/shared/configuration/settings.base.xml <<EOF
<settings>
  <mirrors>
    <mirror>
      <mirrorOf>*</mirrorOf>
      <url>http://$PROXY_IP_ADDR:8081/nexus/content/groups/public</url>
      <id>mirror</id>
    </mirror>
  </mirrors>
</settings>
EOF

  service ruby193-mcollective restart
}

export CONF_BIND_KEY=$BIND_KEY
export CONF_DOMAIN=$OSE_DOMAIN
export CONF_NODE_IP_ADDR=$FLOATING_IP_ADDR
export CONF_NAMED_IP_ADDR=$(sed -ne '/nameserver/ {s/nameserver //; p; }' /etc/resolv.conf)
export CONF_NODE_HOSTNAME=$(hostname).$CONF_DOMAIN
export CONF_INSTALL_COMPONENTS=node
export CONF_KEEP_HOSTNAME=true
export CONF_KEEP_NAMESERVERS=true
export CONF_NO_SCRAMBLE=true

register_channels rhel-x86_64-server-6 rhel-x86_64-server-6-rhscl-1 rhel-x86_64-server-6-ose-2.1-node rhel-x86_64-server-6-ose-2.1-jbosseap jbappplatform-6-x86_64-server-6-rpm jb-ews-2-x86_64-server-6-rpm
install_packages bind-utils

ose_register_dns $CONF_NODE_HOSTNAME A $CONF_NODE_IP_ADDR
ose_install
ose_node_configure
