#!/bin/bash -x

. shared.sh

ose_install() {
  curl -so /tmp/openshift.sh https://raw.githubusercontent.com/openshift/openshift-extras/enterprise-2.1/enterprise/install-scripts/generic/openshift.sh
  chmod 0755 /tmp/openshift.sh
  /tmp/openshift.sh
}

ose_enable_ldap() {
  cp /var/www/openshift/broker/httpd/conf.d/openshift-origin-auth-remote-user-ldap.conf.sample /var/www/openshift/broker/httpd/conf.d/openshift-origin-auth-remote-user.conf
  sed -i -e 's!AuthLDAPURL .*!AuthLDAPURL "ldap://'"$DNS_IP_ADDR"'/ou=Users,dc=demo?cn"!' /var/www/openshift/broker/httpd/conf.d/openshift-origin-auth-remote-user.conf
  cp /var/www/openshift/console/httpd/conf.d/openshift-origin-auth-remote-user-ldap.conf.sample /var/www/openshift/console/httpd/conf.d/openshift-origin-auth-remote-user.conf
  sed -i -e 's!AuthLDAPURL .*!AuthLDAPURL "ldap://'"$DNS_IP_ADDR"'/ou=Users,dc=demo?cn"!' /var/www/openshift/console/httpd/conf.d/openshift-origin-auth-remote-user.conf
  service openshift-broker restart
  service openshift-console restart
}

enable_admin_console() {
  sed -i -e '/ProxyPassReverse \/console/ a\
  ProxyPass /admin-console http://127.0.0.1:8080/admin-console' /etc/httpd/conf.d/000002_openshift_origin_broker_proxy.conf
  sed -i -e '/ProxyPassReverse \/console/ a\
  ProxyPass /assets http://127.0.0.1:8080/assets' /etc/httpd/conf.d/000002_openshift_origin_broker_proxy.conf

  service httpd reload
}

export CONF_BIND_KEY=$BIND_KEY
export CONF_DOMAIN=openshift.demo
export CONF_BROKER_IP_ADDR=$FLOATING_IP_ADDR
export CONF_NAMED_IP_ADDR=$DNS_IP_ADDR
export CONF_INSTALL_COMPONENTS=broker,activemq,datastore
export CONF_KEEP_HOSTNAME=true
export CONF_KEEP_NAMESERVERS=true
export CONF_NO_SCRAMBLE=true

register_channels rhel-x86_64-server-6 rhel-x86_64-server-6-rhscl-1 rhel-x86_64-server-6-ose-2.1-infrastructure rhel-x86_64-server-6-ose-2.1-rhc
install_packages bind-utils

register_dns broker $CONF_DOMAIN A $CONF_BROKER_IP_ADDR
register_dns activemq $CONF_DOMAIN A $CONF_BROKER_IP_ADDR
ose_install
ose_enable_ldap
enable_admin_console
