#!/bin/bash -x

. shared.sh

ose_install() {
  curl -so /tmp/openshift.sh https://raw.githubusercontent.com/openshift/openshift-extras/enterprise-2.1/enterprise/install-scripts/generic/openshift.sh
  chmod 0755 /tmp/openshift.sh
  /tmp/openshift.sh
}

export CONF_BIND_KEY=$BIND_KEY
export CONF_DOMAIN=$OSE_DOMAIN
export CONF_NAMED_IP_ADDR=$FLOATING_IP_ADDR
export CONF_INSTALL_COMPONENTS=named
export CONF_FORWARD_DNS=true
export CONF_KEEP_HOSTNAME=true
export CONF_KEEP_NAMESERVERS=true

register_channels rhel-x86_64-server-6
ose_install
