#!/bin/bash -x

. shared.sh

dns_configure() {
  cat >/etc/named.conf <<EOF
options {
        directory       "/var/named";
        allow-transfer  { none; };
        allow-query     { any; };

        forward only;
        forwarders { $DNS_IP_ADDR; };
        recursion yes;
};

include "/etc/rndc.key";

controls {
        inet 127.0.0.1 port 953
        allow { 127.0.0.1; } keys { rndc-key; };
};
EOF

  rndc-confgen -a -r /dev/urandom
  chown root:named /etc/rndc.key
  chmod 0640 /etc/rndc.key
}

dns_add_domain() {
  cat >>/etc/named.conf <<EOF

zone "$1" IN {
        type master;
        file "dynamic/$1.db";
        allow-update { key $1; } ;
};

include "$1.key";
EOF

  cat >/var/named/dynamic/$1.db <<EOF
@	IN	SOA	ns1	hostmaster	(
					1    ; serial
					60   ; refresh
					15   ; retry
					1800 ; expire
					10)  ; minimum
	NS	ns1
ns1	IN	A	$FLOATING_IP_ADDR
EOF

  cat >/var/named/$1.key <<EOF
key $1 {
  algorithm "HMAC-SHA256";
  secret "$BIND_KEY";
};
EOF

  chown root:named /var/named/$1.key
  chmod 0640 /var/named/$1.key
}

register_channels rhel-x86_64-server-6
install_packages bind
yum_update

dns_configure
dns_add_domain demo
dns_add_domain openshift.demo

chkconfig named on
service named start
lokkit -p 53:udp
